config/routes.rb
MyApp::Application.routes.draw do
  get "sessions/new"

  get "users/new"

  root :to => 'welcome#index'

  
  resources :articles 
  
  namespace :admin do
    resources :articles
    resources :comments
  end
  
  resources :users
  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "users#new"
  
  resources :sessions
  get "log_in" => "sessions#new", :as => "log_in"  
  get "log_out" => "sessions#destroy", :as => "log_out"
  
  resources :comments
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  
  attr_accessible :title, :body, :rating, :user_id
  
  # relations
  has_many :comments, :dependent => :destroy
  belongs_to :user
  
  # validations
  validates :title, :presence => true,
                    :uniqueness => true
                   
   def valid_country_code
                     unless (code =='USA') or (code =='FRA') or (code =='GER') 
                       self.errors[:code] << "Country Code you just entered is not valid"
                     end 
                   end
  # scope
  scope :rating_is_or_above, lambda {|rating| where("rating >= ?", rating) }
  
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
  
  before_filter :require_admin_login
  
  def index
    @articles = Article.all
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(params[:article].merge(:user_id => current_user.id))
    if @article.save
      flash[:notice] = "Article was successfully created."
      redirect_to :action => :index 
    else
      flash[:error] = "Article failed to create."
      render :action => "new"
    end
  end
   
  def edit 
    @article = Article.find_by_id(params[:id])
  end
  
  def update
    @article = Article.find_by_id(params[:id])
    if @article.update_attributes(params[:article])
      flash[:notice] = "Article was successfully updated."
      redirect_to :action => :index 
    else
      flash[:error] = "Article failed to update."
      render :action => "edit"
    end
  end
  
  def destroy 
    @article = Article.find_by_id(params[:id])
    if @article.destroy
      flash[:notice] = "Article was successfully DELETED."
      redirect_to :action => :index 
    else
      flash[:error] = "Article failed to delete."
      redirect_to :action => :index 
    end
  end
  
  def show
    @article = Article.find_by_id(params[:id])
    @comments = @article.comments
    @comment = Comment.new
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_filter :require_login
  #, :only => [:new, :create, :edit, :update, :destroy, :show, :delete]
  
  def index
    @articles = Article.all
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(params[:article].merge(:user_id => current_user.id))
    if @article.save
      flash[:notice] = "Article was successfully created."
      redirect_to :action => :index 
    else
      flash[:error] = "Article failed to create."
      render :action => "new"
    end
  end
   
  def edit 
    @article = Article.find_by_id(params[:id])
  end
  
  def update
    @article = Article.find_by_id(params[:id])
    if @article.update_attributes(params[:article])
      flash[:notice] = "Article was successfully updated."
      redirect_to :action => :index 
    else
      flash[:error] = "Article failed to update."
      render :action => "edit"
    end
  end
  
  def show
    @article = Article.find_by_id(params[:id])
    @comments = @article.comments
    @comment = Comment.new
  end
  

end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_comments.html.erb
<% @comments.each do |comment| %>
  <%= comment.content %>
  <br />
<% end %>

app/views/admin/articles/edit.html.erb
<h1>EDIT ARTICLE</h1>
<%= form_for @article, :url => admin_article_path(@article.id) do |f| %>
  Title: <%= f.text_field :title %>
  <br />
  Body: <%= f.text_area :body %>
  <br />
  <%= f.submit :update %>
<% end %>

app/views/admin/articles/index.html.erb
<h1>LIST OF ARTICLES</h1>
<% @articles.each do |article| %>
  <%= article.title %>
  <%= article.body %>
  <%= link_to "Edit", edit_admin_article_path(article.id) %>
  <%= link_to "Show", admin_article_path(article.id) %>
  <% if current_user.is_admin %>
    <%= link_to "Delete", admin_article_path(article.id), :method => :delete %>
  <% end %>
<br />
<% end %>
<br />
<br />

<%= link_to "Create New Articles", new_admin_article_path %>

app/views/admin/articles/new.html.erb
<h1>NEW ARTICLE</h1>
<%= flash[:notice]%>
<%= form_for @article, :url => admin_articles_path do |f| %>
  <% if @article.errors.any? %>
    <div id="errorExplanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  Title: <%= f.text_field :title %>
  <br />
  Body: <%= f.text_area :body %>
  <br />
  <%= f.submit :save %>
<% end %>

app/views/admin/articles/show.html.erb
<h1>ARTICLE DETAIL</h1>

<!-- Article ID: <%= @article.id %><br /> -->
<h3><%= @article.title %></h3><br />
<%= @article.body %><br /><br />
Rating: <%= @article.rating %><br />
Created: <%= @article.created_at %>
<br />
<br />

<!--to show comments of the current article -->
<div id="comments">
  <h3>Comments:</h3>	
  <%= render :partial => "comments", :locals => {:comments => @comments}  %>
</div>
<br />
<br />

<% unless(current_user.nil?) %> 
  <%= form_for @comment, :url => admin_comments_path, :remote => true do |f| %>
    <%= f.text_area :content %>
    <%= f.hidden_field :article_id, :value => @article.id %>
    <%= submit_tag "Save Comment" %>
  <% end %>
<% end %>
<br />
<br />
<%= link_to "Back", admin_articles_path %>